version: "3"
services:
  app:
    build: ./app
    stdin_open: true
    ports:
      - "3000:3000"
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
    driver: local